In [115]:
# Kaggle contest Titanic: Machine Learning from Disaster 
# https://www.kaggle.com/c/titanic/data
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
data=pd.read_csv("train.csv")
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [93]:
columns_target=['Survived']
columns_train=['Age','Pclass','Sex','Fare']
X=data[columns_train]
Y=data[columns_target]
X['Sex'].isnull().sum()
X['Pclass'].isnull().sum()
X['Fare'].isnull().sum()
X['Age'].isnull().sum()
X['Age']=X['Age'].fillna(x['Age'].median())
d={'male':0,'female':1}
X['Sex']=X['Sex'].apply(lambda x:d[x])
X['Sex'].head()

C:\Users\avin\AppData\Local\conda\conda\envs\mlkaggle\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\Users\avin\AppData\Local\conda\conda\envs\mlkaggle\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()


0    0
1    1
2    1
3    1
4    0
Name: Sex, dtype: int64

In [94]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.33,random_state=42)
clf=svm.LinearSVC()
clf.fit(X_train,Y_train)
print(clf.predict(X_test[0:1]))
print(clf.predict(X_test[0:5]))
print(clf.predict(X_test[0:10]))
print(clf.score(X_test,Y_test))

[0]
[0 0 0 1 1]
[0 0 0 1 1 1 1 0 1 1]
0.7220338983050848


C:\Users\avin\AppData\Local\conda\conda\envs\mlkaggle\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\avin\AppData\Local\conda\conda\envs\mlkaggle\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [105]:
testdata=pd.read_csv("train.csv")
testdata.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [106]:
y=testdata.pop('Survived')


In [109]:
numberic_variable=list(testdata.dtypes[testdata.dtypes != "object"].index )
testdata[numberic_variable].head()

PassengerId  Pclass   Age  SibSp  Parch     Fare
0            1       3  22.0      1      0   7.2500
1            2       1  38.0      1      0  71.2833
2            3       3  26.0      0      0   7.9250
3            4       1  35.0      1      0  53.1000
4            5       3  35.0      0      0   8.0500

In [112]:
testdata["Age"].fillna(testdata.Age.mean(), inplace=True)
testdata.tail()

PassengerId  Pclass                                      Name     Sex  \
886          887       2                     Montvila, Rev. Juozas    male   
887          888       1              Graham, Miss. Margaret Edith  female   
888          889       3  Johnston, Miss. Catherine Helen "Carrie"  female   
889          890       1                     Behr, Mr. Karl Howell    male   
890          891       3                       Dooley, Mr. Patrick    male   

           Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886  27.000000      0      0      211536  13.00   NaN        S  
887  19.000000      0      0      112053  30.00   B42        S  
888  29.699118      1      2  W./C. 6607  23.45   NaN        S  
889  26.000000      0      0      111369  30.00  C148        C  
890  32.000000      0      0      370376   7.75   NaN        Q

In [118]:
model=RandomForestClassifier(n_estimators=100)
model.fit(testdata[numberic_variable],y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [119]:
print("Train Accuracy : ", accuracy_score(y,model.predict(testdata[numberic_variable])))

Train Accuracy :  1.0


In [120]:
test = pd.read_csv("test.csv")
test[numberic_variable].head()
                   

PassengerId  Pclass   Age  SibSp  Parch     Fare
0          892       3  34.5      0      0   7.8292
1          893       3  47.0      1      0   7.0000
2          894       2  62.0      0      0   9.6875
3          895       3  27.0      0      0   8.6625
4          896       3  22.0      1      1  12.2875

In [121]:
test["Age"].fillna(test.Age.mean(), inplace=True)

In [122]:
test=test[numberic_variable].fillna(test.mean()).copy()

In [123]:
y_prediction=model.predict(test[numberic_variable])

In [125]:
y_prediction 

array([0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,

In [133]:

survival_preiction=pd.DataFrame({
    "Passengerid": test["PassengerId"],
    "Survived": y_prediction 
})
survival_preiction.to_csv('titanic.csv',index=False)

In [134]:
survival_preiction

Passengerid  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
5            897         1
6            898         0
7            899         1
8            900         0
9            901         0
10           902         0
11           903         1
12           904         1
13           905         0
14           906         1
15           907         1
16           908         0
17           909         0
18           910         0
19           911         0
20           912         1
21           913         1
22           914         1
23           915         1
24           916         1
25           917         0
26           918         1
27           919         0
28           920         1
29           921         0
..           ...       ...
388         1280         0
389         1281         0
390         1282         1
391         1283         1
392         1284         1
393         1285         0
394         1286         0
395         1287         1
396         1288         0
397         1289         1
398         1290         0
399         1291         0
400         1292         1
401         1293         0
402         1294         1
403         1295         1
404         1296         1
405         1297         0
406         1298         0
407         1299         1
408         1300         0
409         1301         1
410         1302         0
411         1303         1
412         1304         0
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]